#include "RustInitTemplateProvider.h"
#include <sstream>

namespace topo::lang {

// Rust native-lldb formatter, embedded at configure time
// from topo-lang-rust/topo-debug/lldb_formatter.py (see generated
// RustLldbFormatterAsset.cpp).
extern const char kRustLldbFormatterScript[];

std::string RustInitTemplateProvider::generateTopoToml(const std::string& projectName) const {
    std::ostringstream out;
    out << "[project]\n"
        << "name = \"" << projectName << "\"\n\n"
        << "[topo]\n"
        << "root = \"topo/main.topo\"\n\n"
        << "[build]\n"
        << "language = \"rust\"\n"
        << "sources = [\"src/**/*.rs\"]\n"
        << "output = \"" << projectName << "\"\n\n"
        << "[completeness]\n"
        << "ignore_main = true\n";
    return out.str();
}

std::string RustInitTemplateProvider::generateTypeBindings() const {
    return "using i32 = std::rust::i32;\n"
           "using i64 = std::rust::i64;\n"
           "using u32 = std::rust::u32;\n"
           "using u64 = std::rust::u64;\n"
           "using usize = std::rust::usize;\n"
           "using f32 = std::rust::f32;\n"
           "using f64 = std::rust::f64;\n"
           "using bool = std::rust::bool;\n";
}

std::string RustInitTemplateProvider::lldbFormatterRelPath() const {
    return "topo/lldb_formatter.py";
}

std::string RustInitTemplateProvider::lldbFormatterScript() const {
    return kRustLldbFormatterScript;
}

std::string RustInitTemplateProvider::generateLldbInit(
    const std::string& formatterRelPath) const {
    std::ostringstream out;
    out << "# Generated by `topo init` — native-lldb formatter "
           "(zero-install).\n"
        << "#\n"
        << "# Sourced when you run `lldb ./<your-binary>` from this "
           "directory.\n"
        << "# Shows the *logical declared view* of a Topo-optimized variable\n"
        << "# (read from the sibling *.topo-dbg.json `topo build` emits) "
           "instead\n"
        << "# of the raw post-transform layout. Rust symbols are demangled "
           "by\n"
        << "# lldb >= 13. Safe to delete; absence falls back to default "
           "lldb\n"
        << "# formatting. Requires an lldb built with Python scripting.\n"
        << "command script import " << formatterRelPath << "\n";
    return out.str();
}

} // namespace topo::lang
