//! Graph -> `.topo` emission.
//!
//! The deterministic mapping the topo-app design commits to ("deterministic
//! rules for producing `.topo`, not black-magic inference"), not
//! inference — a direct port of
//! `topo-lang-python/runtime/topo/_emit.py`:
//!
//!   * each registered handler emits one `handler` declaration line;
//!   * the flow emits its edges verbatim; stage numbers are *never*
//!     written — deriving the stage topology is core
//!     `PipelineAnalysis`'s job (the flow body accepts pipeline edges
//!     only, per the handler/flow spec).
//!
//! Unlike the Python emitter there is no `using` preamble: the Rust host
//! `.topo` spellings (`i64`/`f64`/`bool`/`string`) are the built-in
//! stdlib forms the grammar accepts directly — verified by
//! `topo --ast-dump` on the emitter output and by `topo-check`
//! completeness against Rust sources (the Rust `handler_flow` fixture
//! likewise carries no preamble). The output is human-readable and
//! hand-editable by construction; that round-trip property is the
//! decisive constraint, so layout favours a stable, obvious form.

use crate::graph::Graph;

/// Render `graph` as `.topo` source text.
pub fn emit_topo(graph: &Graph) -> String {
    let mut lines: Vec<String> = vec![
        "// Generated by topo-app (Rust). Human-readable and round-trip".to_string(),
        "// safe: editing this file and reading it back yields the same".to_string(),
        "// logic graph. Hand edits survive; this is a view, not an IR.".to_string(),
        String::new(),
        format!("namespace {} {{", graph.namespace),
        "  public:".to_string(),
    ];

    for h in &graph.handlers {
        lines.push(format!("    {}", h.signature()));
    }

    if let Some(flow) = &graph.flow {
        lines.push(String::new());
        lines.push(format!("    flow {} {{", flow.name));
        for e in &flow.edges {
            let tgt = match &e.target {
                None => "void".to_string(),
                Some(t) => t.clone(),
            };
            lines.push(format!("      {} -> {};", e.source, tgt));
        }
        lines.push("    }".to_string());
    }

    lines.push("}".to_string());
    lines.push(String::new());
    lines.join("\n")
}
