//! Graph -> .topo emission.
//!
//! Byte-for-byte the same emitter form as the Python runtime bridge's
//! `_emit.py`. The topo-app design's decisive constraint is that the framework
//! and `.topo` are two reversible views of one logic structure; the
//! static path is just another `.topo` producer, so it must emit the *same*
//! surface the runtime bridge does — otherwise round-trip equivalence
//! against the runtime path could not be byte-compared.
//!
//! The only intentional difference from the Python emitter is the
//! preamble: the scalar aliases bind the Rust stdlib spelling
//! (`std::rust::...`) instead of `std::python::...`, because the host
//! language is Rust. The structural body (namespace / `public:` /
//! handler lines / flow edges) is identical.

use crate::graph::Graph;

// Scalar aliases the Rust host binds, matching the Rust handler/flow
// spec fixture's stdlib vocabulary (i64 / f64 / bool / string) so the
// emitted .topo consumes the same stdlib types the rest of the
// toolchain expects for a Rust host.
const PREAMBLE: &str = "using i64 = std::rust::i64;\n\
using f64 = std::rust::f64;\n\
using bool = std::rust::bool;\n\
using string = std::rust::String;";

pub fn emit_topo(graph: &Graph) -> String {
    let mut lines: Vec<String> = vec![
        "// Generated by topo-app (Rust, static). Human-readable and".to_string(),
        "// round-trip safe: editing this file and reading it back yields".to_string(),
        "// the same logic graph. Hand edits survive; a view, not an IR.".to_string(),
        String::new(),
        PREAMBLE.to_string(),
        String::new(),
        format!("namespace {} {{", graph.namespace),
        "  public:".to_string(),
    ];
    for h in &graph.handlers {
        lines.push(format!("    {}", h.signature()));
    }
    if let Some(flow) = &graph.flow {
        lines.push(String::new());
        lines.push(format!("    flow {} {{", flow.name));
        for e in &flow.edges {
            let tgt = if e.is_terminal() {
                "void".to_string()
            } else {
                e.target.clone().unwrap()
            };
            lines.push(format!("      {} -> {};", e.source, tgt));
        }
        lines.push("    }".to_string());
    }
    lines.push("}".to_string());
    lines.push(String::new());
    lines.join("\n")
}
